#
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

def fib_seq():
    fib = [1, 2]
    curr_index = 2
    while True:
        next_num = fib[curr_index - 2] + fib[curr_index - 1]

        if next_num > 4000000:
            break
        else:
            fib.append(next_num)
            curr_index += 1

    return fib


total = 0
fib_numbers = fib_seq()

for i in range(len(fib_numbers)):
    if fib_numbers[i] % 2 == 0:
        total += fib_numbers[i]

print(total)
